#Write a program to display a big T pattern 


print("=============================")
print("              =              ")
print("              =              ")
print("              =              ")
print("              =              ")
print("              =              ")
print("              =              ")
print("||")
print("||")
print("||")
print("||")
print("||")
print("||")
print("||")
print("||")
print("||")
print("||")
print("||")
print("=================================")
print("||   clive co-operate          ||")
print("||   we've got you!            ||")
print("||   ever since 2004           ||")
print("=================================")